"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";

type Row={id:string;batch_no:string;production_date:string;raw_material_kg:number;output_kg:number;material_cost:number;labor_cost:number;energy_cost:number;overhead_cost:number};
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0);

export default function Home(){
 const [session,setSession]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[rows,setRows]=useState<Row[]>([]);
 const [f,setF]=useState({batch_no:"",production_date:new Date().toISOString().slice(0,10),raw_material_kg:"",output_kg:"",material_cost:"",labor_cost:"",energy_cost:"",overhead_cost:"",operator_name:"",notes:""});
 const load=async()=>{if(!supabase)return;const {data}=await supabase.from("production_analysis").select("*").order("production_date",{ascending:false}).limit(50);setRows((data||[]) as Row[])};
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const x=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>x.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 const t=useMemo(()=>{let r=0,o=0,c=0;rows.forEach(x=>{r+=+x.raw_material_kg;o+=+x.output_kg;c+=+x.material_cost+ +x.labor_cost+ +x.energy_cost+ +x.overhead_cost});return{r,o,s:r-o,y:r?o/r*100:0,c,h:o?c/o:0}},[rows]);
 const chart=[...rows].reverse().slice(-10).map(x=>({batch:x.batch_no,bahan:+x.raw_material_kg,jadi:+x.output_kg}));
 const login=async()=>{if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?.message||"Berhasil masuk.")};
 const signup=async()=>{if(!supabase)return;const {error}=await supabase.auth.signUp({email,password});setMsg(error?.message||"Akun dibuat. Cek email jika konfirmasi aktif.")};
 const save=async()=>{if(!supabase)return;const raw=+f.raw_material_kg,out=+f.output_kg;if(!f.batch_no||raw<=0||out<0){setMsg("Isi nomor batch, bahan baku dan barang jadi.");return}const {error}=await supabase.from("production_batches").insert({...f,raw_material_kg:raw,output_kg:out,material_cost:+f.material_cost||0,labor_cost:+f.labor_cost||0,energy_cost:+f.energy_cost||0,overhead_cost:+f.overhead_cost||0});setMsg(error?.message||"Batch tersimpan.");if(!error){setF({...f,batch_no:"",raw_material_kg:"",output_kg:"",material_cost:"",labor_cost:"",energy_cost:"",overhead_cost:"",notes:""});load()}};
 if(!supabase)return <main className="center"><div className="card auth"><h1>Konfigurasi belum siap</h1><p className="muted">GitHub Actions perlu dua secrets Supabase.</p></div></main>;
 if(!session)return <main className="center"><div className="card auth"><h1>🔥 Portal Manajemen Arang</h1><p className="muted">Masuk untuk mengelola usaha.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login}>Masuk</button><button className="secondary" onClick={signup}>Buat akun</button>{msg&&<p className="notice">{msg}</p>}</div></main>;
 return <main><header className="top"><div><div className="eyebrow">PORTAL USAHA</div><h1>Manajemen Arang</h1></div><button className="secondary small" onClick={()=>supabase.auth.signOut()}>Keluar</button></header>
 <section className="grid cards"><div className="stat"><span>Bahan baku</span><b>{t.r.toLocaleString("id-ID")} kg</b></div><div className="stat"><span>Barang jadi</span><b>{t.o.toLocaleString("id-ID")} kg</b></div><div className="stat"><span>Rendemen</span><b>{t.y.toFixed(1)}%</b></div><div className="stat"><span>HPP / kg</span><b>{rupiah(t.h)}</b></div></section>
 <section className="grid two"><div className="card"><h2>Input produksi</h2><div className="form">{(["batch_no","production_date","raw_material_kg","output_kg","material_cost","labor_cost","energy_cost","overhead_cost","operator_name","notes"] as const).map(k=><input key={k} type={k==="production_date"?"date":"text"} inputMode={k.includes("cost")||k.includes("kg")?"decimal":"text"} placeholder={k==="batch_no"?"No. batch":k==="production_date"?"Tanggal":k==="raw_material_kg"?"Bahan baku (kg)":k==="output_kg"?"Barang jadi (kg)":k==="material_cost"?"Biaya bahan":k==="labor_cost"?"Tenaga kerja":k==="energy_cost"?"BBM / energi":k==="overhead_cost"?"Overhead":k==="operator_name"?"Operator":"Catatan"} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}</div><button onClick={save}>Simpan batch</button>{msg&&<p className="notice">{msg}</p>}</div>
 <div className="card"><h2>Bahan baku → barang jadi</h2><div className="chart">{chart.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="batch"/><YAxis/><Tooltip/><Bar dataKey="bahan" name="Bahan baku"/><Bar dataKey="jadi" name="Barang jadi"/></BarChart></ResponsiveContainer>:<p className="muted">Belum ada data produksi.</p>}</div><div className="result"><div><span>Penyusutan</span><b>{Math.max(t.s,0).toLocaleString("id-ID")} kg</b></div><div><span>Total biaya</span><b>{rupiah(t.c)}</b></div></div></div></section>
 <section className="grid"><div className="card"><h2>Riwayat produksi</h2><div className="table"><table><thead><tr><th>Batch</th><th>Tanggal</th><th>Bahan</th><th>Jadi</th><th>Rendemen</th><th>HPP/kg</th></tr></thead><tbody>{rows.map(x=>{const r=+x.raw_material_kg,o=+x.output_kg,c=+x.material_cost+ +x.labor_cost+ +x.energy_cost+ +x.overhead_cost;return <tr key={x.id}><td>{x.batch_no}</td><td>{x.production_date}</td><td>{r.toLocaleString("id-ID")}</td><td>{o.toLocaleString("id-ID")}</td><td>{r?(o/r*100).toFixed(1):0}%</td><td>{rupiah(o?c/o:0)}</td></tr>})}</tbody></table></div></div></section></main>
}